using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace LeetCode
{
    //Given two strings s and t which consist of only lowercase letters.
    //String t is generated by random shuffling string s and then add one more letter at a random position.
    //Find the letter that was added in t.

    public partial class Solution
    {
        public char FindTheDifference(string s, string t)
        {
            //先加T的最後一個字元
            int sum = t[t.Length -1];

            for (int i = 0; i < t.Length - 1; i++)
            {
                //T加總
                sum += t[i];
                //扣掉S
                sum -= s[i];
                
            }
            //相差的值
            return (char)(sum);
        }
    }
}
